# yaml-language-server: $schema=./settings.schema.yaml

timelines:
  ENGM:
    defaults:
      defaultArrivalLabelLayoutId: osloArr
      defaultDepartureLabelLayoutId: osloDep

    runwayBased:
      - timelineTitle: "01ALL"
        right: ["01L", "01R"]

      - timelineTitle: "19ALL"
        right: ["19L", "19R"]

      - timelineTitle: "19R/19L"
        left: ["19R"]
        right: ["19L"]

      - timelineTitle: "01L/01R"
        left: ["01L"]
        right: ["01R"]

    meteringPointBased:
      - timelineTitle: "BAVAD / TITLA"
        left: ["BAVAD"]
        right: ["TITLA"]

      - timelineTitle: "VALPU / INSUV"
        left: ["VALPU"]
        right: ["INSUV"]

  ENBR:
    defaults:
      defaultArrivalLabelLayoutId: osloArr
      defaultDepartureLabelLayoutId: osloDep

    runwayBased:
      - timelineTitle: "BR17"
        right: ["17"]

      - timelineTitle: "BR35"
        right: ["35"]

      - timelineTitle: "ENBR ALL"
        right: ["17", "35"]

    meteringPointBased: []

arrivalLabelLayouts:
  osloArr:
    - {src: assignedRunway, w: 4}
    - {src: assignedStar, w: 4, maxLen: 3}
    - {src: callSign, w: 8}
    - {src: aircraftType, w: 5}
    - {src: wakeCategory, w: 2}
    - {src: timeToLoseOrGain, w: 4, align: right}
    - {src: distanceBehindPreceding, w: 5, align: right}

  simpleLayout:
    - {src: assignedRunway, w: 4}
    - {src: callSign, w: 8}

departureLabelLayouts:
  osloDep:
    - {src: assignedRunway, w: 4}
    - {src: callSign, w: 8}
    - {src: aircraftType, w: 5}

connectionConfig:
  atcClient:
    host: "localhost"
    port: 12345
  masterSlaveApi:
    host: "https://aman-dman-api.fly.dev"

theme: "JTattoo"
